use anyhow::{anyhow, Result};
use std::path::{Path, PathBuf};

#[cfg(target_os = "macos")]
pub fn find_app_bundle(exe_path: &Path) -> Option<PathBuf> {
    let mut cur = exe_path;
    while let Some(parent) = cur.parent() {
        if parent.extension().and_then(|s| s.to_str()) == Some("app") {
            return Some(parent.to_path_buf());
        }
        cur = parent;
    }
    None
}

#[cfg(unix)]
pub fn generate_launcher_script(canonical_exe: &Path) -> String {
    #[cfg(target_os = "macos")]
    let app_bundle = find_app_bundle(canonical_exe);
    #[cfg(not(target_os = "macos"))]
    let app_bundle: Option<PathBuf> = None;

    let launch_command = if let Some(ref app_path) = app_bundle {
        format!("open -n -a {:?} --args \"${{ARGS[@]}}\"", app_path.display().to_string())
    } else {
        format!("nohup {:?} \"${{ARGS[@]}}\" >/dev/null 2>&1 &", canonical_exe.display().to_string())
    };

    format!(
r#"#!/usr/bin/env bash
# Generated by Zenvi - do not edit manually

ARGS=()
for arg in "$@"; do
    if [ -e "$arg" ]; then
        if [ -d "$arg" ]; then
            ARGS+=("$(cd "$arg" && pwd)")
        else
            DIR="$(cd "$(dirname "$arg")" && pwd)"
            ARGS+=("$DIR/$(basename "$arg")")
        fi
    else
        ARGS+=("$arg")
    fi
done

if [ $# -eq 0 ]; then
    ARGS+=("$(pwd)")
fi

{}
"#,
        launch_command
    )
}

#[cfg(windows)]
pub fn generate_launcher_script(canonical_exe: &Path) -> String {
    format!(
r#"@echo off
rem Generated by Zenvi - do not edit manually
start "" {:?} %*
"#,
        canonical_exe.display().to_string()
    )
}

pub fn install_shell_command() -> Result<PathBuf> {
    let current_exe = std::env::current_exe()
        .map_err(|e| anyhow!("Failed to get current executable path: {}", e))?;
    let canonical_exe = current_exe.canonicalize().unwrap_or(current_exe);

    #[cfg(unix)]
    let (bin_dir, script_name) = {
        let home = std::env::var("HOME")
            .map_err(|_| anyhow!("Environment variable $HOME is not set"))?;
        (PathBuf::from(home).join(".local").join("bin"), "zenvi")
    };

    #[cfg(windows)]
    let (bin_dir, script_name) = {
        let base = std::env::var("USERPROFILE")
            .or_else(|_| std::env::var("LOCALAPPDATA"))
            .map_err(|_| anyhow!("Environment variable %USERPROFILE% or %LOCALAPPDATA% is not set"))?;
        (PathBuf::from(base).join(".local").join("bin"), "zenvi.cmd")
    };

    std::fs::create_dir_all(&bin_dir)
        .map_err(|e| anyhow!("Failed to create directory {}: {}", bin_dir.display(), e))?;

    let script_path = bin_dir.join(script_name);

    // Remove existing file or symlink if it exists
    if script_path.exists() || script_path.is_symlink() {
        let _ = std::fs::remove_file(&script_path);
    }

    let script_content = generate_launcher_script(&canonical_exe);
    std::fs::write(&script_path, script_content)
        .map_err(|e| anyhow!("Failed to write launcher script at {}: {}", script_path.display(), e))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let perms = std::fs::Permissions::from_mode(0o755);
        let _ = std::fs::set_permissions(&script_path, perms);
    }

    log::info!(
        "Successfully installed non-blocking shell command: {}",
        script_path.display()
    );

    Ok(script_path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[cfg(target_os = "macos")]
    #[test]
    fn test_find_app_bundle() {
        let p = PathBuf::from("/Applications/Zenvi.app/Contents/MacOS/zenvi");
        let app = find_app_bundle(&p);
        assert_eq!(app, Some(PathBuf::from("/Applications/Zenvi.app")));

        let p2 = PathBuf::from("/Users/harry/dev/zenvi/target/release/zenvi");
        assert_eq!(find_app_bundle(&p2), None);
    }

    #[cfg(unix)]
    #[test]
    fn test_generate_launcher_script() {
        #[cfg(target_os = "macos")]
        {
            let app_exe = PathBuf::from("/Applications/Zenvi.app/Contents/MacOS/zenvi");
            let script = generate_launcher_script(&app_exe);
            assert!(script.contains("open -n -a"));
            assert!(script.contains("/Applications/Zenvi.app"));
        }

        let bin_exe = PathBuf::from("/Users/harry/dev/zenvi/target/release/zenvi");
        let script2 = generate_launcher_script(&bin_exe);
        assert!(script2.contains("nohup"));
        assert!(script2.contains("/Users/harry/dev/zenvi/target/release/zenvi"));
    }

    #[test]
    fn test_install_shell_command_creates_executable_script() {
        let res = install_shell_command();
        assert!(res.is_ok(), "install_shell_command should succeed: {:?}", res.err());
        let script_path = res.unwrap();
        assert!(script_path.exists());

        let content = std::fs::read_to_string(&script_path).expect("Should read script content");
        #[cfg(unix)]
        assert!(content.starts_with("#!/usr/bin/env bash"));
        #[cfg(windows)]
        assert!(content.starts_with("@echo off"));

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let metadata = std::fs::metadata(&script_path).expect("Should get metadata");
            let mode = metadata.permissions().mode();
            assert_eq!(mode & 0o111, 0o111, "File should have executable permissions");
        }
    }
}
